version: '3'
services:
  efp-frontend:
    image: efp-frontend
    networks:
      - efp
  efp-reverse-proxy:
    image: efp-reverse-proxy
    networks:
      - efp
    ports:
      - '8080:80'
    depends_on:
      - efp-backend
      - efp-frontend
  efp-backend:
    image: efp-backend
    networks:
      - efp
  efp-mongo:
    image: mongo
    # all the data will be lost after we restart the container
    # this volume will save the data on the host disc
    # this should NOT be saved inside this git repo
    volumes:
      - ./mongo:/data/db
    networks:
      - efp
    ports:
      - "27018:27017"
networks:
  efp: